---
- hosts: web
  become: true
  tasks:
    - name: save date
      set_fact:
        msg: '{{ ansible_date_time.date }}'
    - name: save service_name
      set_fact:
        server_name: '{{ ansible_hostname }}'
    - name: copy index.html
      template:
        src: ../files/index.html.j2
        dest: /usr/share/nginx/html/index.html
      notify: restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
